version: "3.8"

services:
    frontend:
        image: familyresearchcouncil/next-template:staging
        deploy:
            replicas: 1
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.next-template-staging.rule=Host(`next-template.frc.org`)"
                - "traefik.http.services.next-template-staging.loadbalancer.server.port=3000"
            placement:
                constraints:
                    - node.role == worker
        command: npm run start
        networks:
            - traefik
            - default


networks:
    traefik:
        external: true
